"""Curated shape grammars for coherent geometric compositions."""

from __future__ import annotations

from pixel_forge.generators.geometric_orbit.parameters import (
    CompositionStyle,
    ShapeGrammar,
)

SHAPE_GRAMMARS: dict[CompositionStyle, ShapeGrammar] = {
    "bubble-field": ShapeGrammar(
        name="bubble-field",
        primary_shape="circle",
        secondary_shape="ring",
        tertiary_shape="square",
        distribution="scattered-orbit",
        size_distribution="multi-scale",
        min_count=34,
        max_count=58,
        ring_count=2,
        angular_jitter=0.15,
        radial_jitter=0.09,
        large_shape_probability=0.12,
        secondary_probability=0.20,
        tertiary_probability=0.08,
        allow_outline_only=True,
        background_choices=("broad-ribbons", "split-diagonal", "quiet-field"),
    ),
    "double-square-crown": ShapeGrammar(
        name="double-square-crown",
        primary_shape="square",
        secondary_shape="diamond",
        tertiary_shape=None,
        distribution="double-ring",
        size_distribution="uniform-jitter",
        min_count=28,
        max_count=42,
        ring_count=2,
        angular_jitter=0.035,
        radial_jitter=0.018,
        large_shape_probability=0.04,
        secondary_probability=0.32,
        tertiary_probability=0.0,
        allow_outline_only=False,
        background_choices=("angular-wedges", "crossing-beams", "split-diagonal"),
    ),
    "triangle-explosion": ShapeGrammar(
        name="triangle-explosion",
        primary_shape="triangle",
        secondary_shape="diamond",
        tertiary_shape="line",
        distribution="radial-burst",
        size_distribution="wide",
        min_count=22,
        max_count=38,
        ring_count=2,
        angular_jitter=0.12,
        radial_jitter=0.12,
        large_shape_probability=0.20,
        secondary_probability=0.18,
        tertiary_probability=0.10,
        allow_outline_only=True,
        background_choices=("crossing-beams", "angular-wedges", "broad-ribbons"),
    ),
    "neon-orbit": ShapeGrammar(
        name="neon-orbit",
        primary_shape="circle",
        secondary_shape="capsule",
        tertiary_shape="ring",
        distribution="single-ring",
        size_distribution="multi-scale",
        min_count=18,
        max_count=30,
        ring_count=1,
        angular_jitter=0.05,
        radial_jitter=0.03,
        large_shape_probability=0.10,
        secondary_probability=0.34,
        tertiary_probability=0.18,
        allow_outline_only=True,
        background_choices=("split-diagonal", "crossing-beams", "quiet-field"),
    ),
    "radial-capsules": ShapeGrammar(
        name="radial-capsules",
        primary_shape="capsule",
        secondary_shape="circle",
        tertiary_shape=None,
        distribution="single-ring",
        size_distribution="uniform-jitter",
        min_count=22,
        max_count=34,
        ring_count=1,
        angular_jitter=0.025,
        radial_jitter=0.015,
        large_shape_probability=0.03,
        secondary_probability=0.12,
        tertiary_probability=0.0,
        allow_outline_only=False,
        background_choices=("split-diagonal", "broad-ribbons", "quiet-field"),
    ),
    "symbolic-minimal": ShapeGrammar(
        name="symbolic-minimal",
        primary_shape="square",
        secondary_shape="circle",
        tertiary_shape="line",
        distribution="single-ring",
        size_distribution="uniform-jitter",
        min_count=7,
        max_count=12,
        ring_count=1,
        angular_jitter=0.08,
        radial_jitter=0.035,
        large_shape_probability=0.08,
        secondary_probability=0.35,
        tertiary_probability=0.25,
        allow_outline_only=True,
        background_choices=("quiet-field", "split-diagonal", "broad-ribbons"),
    ),
    "geometric-sun": ShapeGrammar(
        name="geometric-sun",
        primary_shape="capsule",
        secondary_shape="triangle",
        tertiary_shape="line",
        distribution="single-ring",
        size_distribution="uniform-jitter",
        min_count=24,
        max_count=40,
        ring_count=1,
        angular_jitter=0.02,
        radial_jitter=0.01,
        large_shape_probability=0.06,
        secondary_probability=0.20,
        tertiary_probability=0.10,
        allow_outline_only=False,
        background_choices=("broad-ribbons", "angular-wedges", "split-diagonal"),
    ),
    "scattered-constellation": ShapeGrammar(
        name="scattered-constellation",
        primary_shape="circle",
        secondary_shape="square",
        tertiary_shape="ring",
        distribution="constellation",
        size_distribution="multi-scale",
        min_count=30,
        max_count=52,
        ring_count=2,
        angular_jitter=0.20,
        radial_jitter=0.14,
        large_shape_probability=0.14,
        secondary_probability=0.24,
        tertiary_probability=0.14,
        allow_outline_only=True,
        background_choices=("quiet-field", "split-diagonal", "crossing-beams"),
    ),
}

COMPOSITION_STYLES: tuple[CompositionStyle, ...] = tuple(SHAPE_GRAMMARS)
